customer:
  property: Credit Profile Dev
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/credit_db
logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG

app:
  testProp: Hola Mundo desde Config Server Dev
