customer:
  property: Customer Profile Prod
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer_db
logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG

app:
  testProp: Hola Mundo desde Config Server
